-- Shared medicine schedule for one DiVie account used on two devices.
-- The active UI role (family/elder) is device-local; the schedule belongs to the account.

create table if not exists public.medicine_reminders (
  id bigint generated always as identity primary key,
  account_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (length(trim(name)) between 1 and 120),
  time text not null check (time ~ '^(?:[01][0-9]|2[0-3]):[0-5][0-9]$'),
  note text not null default '' check (length(note) <= 300),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists medicine_reminders_account_time_idx
  on public.medicine_reminders(account_id, time);

alter table public.medicine_reminders enable row level security;

drop policy if exists "Users can read own medicine reminders" on public.medicine_reminders;
create policy "Users can read own medicine reminders"
  on public.medicine_reminders for select to authenticated
  using ((select auth.uid()) = account_id);

drop policy if exists "Users can create own medicine reminders" on public.medicine_reminders;
create policy "Users can create own medicine reminders"
  on public.medicine_reminders for insert to authenticated
  with check ((select auth.uid()) = account_id);

drop policy if exists "Users can update own medicine reminders" on public.medicine_reminders;
create policy "Users can update own medicine reminders"
  on public.medicine_reminders for update to authenticated
  using ((select auth.uid()) = account_id)
  with check ((select auth.uid()) = account_id);

drop policy if exists "Users can delete own medicine reminders" on public.medicine_reminders;
create policy "Users can delete own medicine reminders"
  on public.medicine_reminders for delete to authenticated
  using ((select auth.uid()) = account_id);

create or replace function public.touch_medicine_reminder_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists medicine_reminders_touch_updated_at on public.medicine_reminders;
create trigger medicine_reminders_touch_updated_at
before update on public.medicine_reminders
for each row execute function public.touch_medicine_reminder_updated_at();

create table if not exists public.medicine_reminder_events (
  id bigint generated by default as identity primary key,
  account_id uuid not null references auth.users(id) on delete cascade,
  reminder_id bigint not null references public.medicine_reminders(id) on delete cascade,
  scheduled_on date not null,
  status text not null check (status in ('taken', 'snoozed', 'skipped')),
  taken_at timestamptz,
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (account_id, reminder_id, scheduled_on)
);

create index if not exists medicine_reminder_events_account_day_idx
  on public.medicine_reminder_events(account_id, scheduled_on);

alter table public.medicine_reminder_events enable row level security;

drop policy if exists "Users can read own medicine reminder events" on public.medicine_reminder_events;
create policy "Users can read own medicine reminder events"
  on public.medicine_reminder_events for select to authenticated
  using ((select auth.uid()) = account_id);

drop policy if exists "Users can create own medicine reminder events" on public.medicine_reminder_events;
create policy "Users can create own medicine reminder events"
  on public.medicine_reminder_events for insert to authenticated
  with check ((select auth.uid()) = account_id);

drop policy if exists "Users can update own medicine reminder events" on public.medicine_reminder_events;
create policy "Users can update own medicine reminder events"
  on public.medicine_reminder_events for update to authenticated
  using ((select auth.uid()) = account_id)
  with check ((select auth.uid()) = account_id);

drop policy if exists "Users can delete own medicine reminder events" on public.medicine_reminder_events;
create policy "Users can delete own medicine reminder events"
  on public.medicine_reminder_events for delete to authenticated
  using ((select auth.uid()) = account_id);

grant select, insert, update, delete on table
  public.medicine_reminders,
  public.medicine_reminder_events
to authenticated;

grant usage, select on all sequences in schema public to authenticated;

drop trigger if exists medicine_reminder_events_touch_updated_at on public.medicine_reminder_events;
create trigger medicine_reminder_events_touch_updated_at
before update on public.medicine_reminder_events
for each row execute function public.touch_medicine_reminder_updated_at();
